name: CICD

on:
  push:
    branches: [ "master" ]

concurrency:
  group: CICD
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: docker.io/korenp/unleash-exercise:${{ vars.NEXT_VERSION }}

  CD:
    needs: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .terraform
    permissions:
      repository-projects: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -recursive -check

    - name: Terraform Validate
      run: terraform validate

    - name: Download Terraform State Artifact
      uses: actions/download-artifact@v4
      continue-on-error: true
      with:
        name: terraform.tfstate
        path: .terraform
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ vars.LATEST_ARTIFACT_RUN_ID }}

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        ENVIRONMENT: production
        BUCKET_NAME: production-bucket
        IMAGE_TAG: ${{ vars.NEXT_VERSION }}
      run: terraform apply -auto-approve -var environment=$ENVIRONMENT -var bucket_name=$BUCKET_NAME -var image_tag=$IMAGE_TAG

    - uses: actions/upload-artifact@v4
      with:
        name: terraform.tfstate
        path: .terraform/terraform.tfstate

    - name: Update LATEST_ARTIFACT_RUN_ID, NEXT_VERSION Variables
      env:
        GITHUB_TOKEN: ${{ secrets.VARIABLES_ACCESS_TOKEN }}
      run: |
        gh variable set LATEST_ARTIFACT_RUN_ID --body "${{ github.run_id }}"
        gh variable set NEXT_VERSION --body "`echo ${{ vars.NEXT_VERSION }} | awk -F . '{print $1"."$2"."$3+1}'`"